version: "3.7"
services:
  postgresql:
    image: postgres:12
    networks:
      - shop
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes:/var/lib/postgresql/data


  shop-api:
    build:
      context: ./
    networks:
      - shop
    environment:
      - DB_HOST=postgresql
      - DB_USER_NAME=postgres
      - DB_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "8080:8080"



networks:
  shop:
    driver: bridge
    internal: False


